### PR TITLE
Add source content

### LINKED ISSUE #6: No sourcesContent
There's no `sourcesContent` generated in the final source map.

### PR DESCRIPTION
**Pull request by aandis**
Closes #6

### CODE REVIEW

**Comment by aandis** [comment]
Ping @azu

**Review by azu — APPROVED** [review]
LGTM

**Comment by aandis** [comment]
@azu would be great if you can release this. :)

**Comment by azu** [comment]
@aandis I've released https://github.com/azu/multi-stage-sourcemap/releases/tag/v0.3.1

Thanks :)

**Pull request merged**
